language: scala
scala:
- 2.11.11
notifications:
  slack:
    rooms:
      secure: VxqPXE2uUqAsezpQp7IR9lUEUnpyvbycR2fS1v2HIxw3ZLIKdtLe/J5/Fk3oR3LA34X3nDc4zz0QgO29Ug9MuMRuqv4sSnUCy09VvAy/7Z1BqfA7N0Bglf3PHrBwXHR7y4+JLlk3qh3VjvBXZ2daIL+SAX3FODucGxIQTMpR9fV/+ln6HyMv3UwaB5FuGKFOu+f0vfinTjZDPrVS8BUVBagP/oMil4ppCC4voGm0Lb/ZoZ6fYrifsxIcMmXfHyhgg8EX8pvaF1QFsq3B2B1vbyvTDJUn6L8Hdl+/glx2rTroH67oBqrheRqMjwRIFa4cETHJYJVfN/NiuZESahvQfL1qtPWJjkGImfwi5O6fS5XqTD1pUhJciIQMpsyoKMiqAo4bCW+yluqJKGBe8m71Gc0X4d6KxnUlZnLFIDcnxAehSsVIl4IpkTxTSjymUtH1HD9XYmQyV/r6eVI8dVfBOqlpuGMu1wWYmp0pPty96rxMJVUC0GJtEn/J5BAoyUJfS9qdGjSZVnUTzINHPG+tvLNKaPLKt2NNi1LcewuvEc/EYPnUSSc05Dxy+8MDNwet0JFTpXgUURE0uqevpX8hao1yM+vGNtYWSUdJR/xyRiDRlRKIphL2vXjXLxB52oDsQI5RzETgfKEi/eNMQO7OcxW3RpkRSz/wgaKQ6k788Fs=
