language: scala
scala:
- 2.11.11
script:
- "sbt test"
- "sbt package"
notifications:
  slack:
    rooms:
      secure: VxqPXE2uUqAsezpQp7IR9lUEUnpyvbycR2fS1v2HIxw3ZLIKdtLe/J5/Fk3oR3LA34X3nDc4zz0QgO29Ug9MuMRuqv4sSnUCy09VvAy/7Z1BqfA7N0Bglf3PHrBwXHR7y4+JLlk3qh3VjvBXZ2daIL+SAX3FODucGxIQTMpR9fV/+ln6HyMv3UwaB5FuGKFOu+f0vfinTjZDPrVS8BUVBagP/oMil4ppCC4voGm0Lb/ZoZ6fYrifsxIcMmXfHyhgg8EX8pvaF1QFsq3B2B1vbyvTDJUn6L8Hdl+/glx2rTroH67oBqrheRqMjwRIFa4cETHJYJVfN/NiuZESahvQfL1qtPWJjkGImfwi5O6fS5XqTD1pUhJciIQMpsyoKMiqAo4bCW+yluqJKGBe8m71Gc0X4d6KxnUlZnLFIDcnxAehSsVIl4IpkTxTSjymUtH1HD9XYmQyV/r6eVI8dVfBOqlpuGMu1wWYmp0pPty96rxMJVUC0GJtEn/J5BAoyUJfS9qdGjSZVnUTzINHPG+tvLNKaPLKt2NNi1LcewuvEc/EYPnUSSc05Dxy+8MDNwet0JFTpXgUURE0uqevpX8hao1yM+vGNtYWSUdJR/xyRiDRlRKIphL2vXjXLxB52oDsQI5RzETgfKEi/eNMQO7OcxW3RpkRSz/wgaKQ6k788Fs=
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: aWGMoaHZee1cneTzY68RggY4y0KXSe9MieUIyG13OyUicHe2wNiAa/g8WOJ1+O9LDdrCN6mEe9eOU4tlthlDijfrBdMJWE/ievWuFg8S489cIiFZdOiiyxYzY70+xm5omzv2M/h8zHF8iQM6VAXtD2tojXHpXMKpQPYr/kkpkdu+ZVfizDCddlzz8m0l3AD643J4F1186P29RfWW1wTYZPJ8i69M/Y9tgfuzgXN0CRP/EJ3DKPzC+KrI7+rc3pqwma3wOj7KGZZv9RENcj56nJ+0R10p0vCIcGZ/nacDYUf7G1Foy7M3tjdw27sBAmFhrEDwIcm4vu2WPtrsqRlEy0u0aU0/t/HWssfl4gSX1xPBJsGdWVYpAiKZgp1Q7WxfvGvHFPtgAy4r8ZDB2vwOdtgN63/TgYl+ghWScJs5LggvZ7hEzqkeblj7jH4Qj+SeUHR8G7sItN1Tf/JEIEL09/nwZliHTaB3KaC+G9y+niHSVj8FLLGbtImT3rzPMiXnE0APjmcfWiAJWEFMyz3scoqFtLBatu4a1E99HJVcC7URC1/thOMLIDhjm1L+K/LQ9KCDxz6uoC3dh8EZ6z3icsMJ/gtNQEtZLyAOePCZLRvK5O0Wm2NKjwrcgvV7viLgpzJ0PXGrmFZBWvy1yGH94gTVlhsTD4CKfglF4DZHSlU=
  file: target/scala-2.11/jobs-spark-il_2.11-0.1.2.jar
  on:
    tags: true
